### ISSUE TITLE
【功能请求】自动刷新画中画

### ISSUE THREAD

**Issue by std4453** [bilibili-helper/bilibili-helper-o#560]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 72.0.3626.109
3. 扩展版本: 1.2.0.beta6

### 重现步骤/尝试的解决方案
1. 打开任何多p视频/多集番剧，使用画中画功能将视频显示为画中画
2. （自动/手动）切换p
3. 画中画维持之前一p的画面，新p在原播放器中播放
4. 重新点击画中画按钮可以解决问题

是否可能在检测到换p的时候自动画中画？

**Comment by jjj201200** [comment]
可以！感谢您的建议！

**Comment by jjj201200** [comment]
非常遗憾，目前无法做到“自动切分P时自动窗口化”，而只能“手动切分P时自动窗口化”。
详见：[link](https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture)中提到的如下6条中的第六条。
The promise may reject for any of the following reasons:

- Picture-in-Picture is not supported by the system.
- Document is not allowed to use Picture-in-Picture due to a restrictive feature policy.
- Video metadata have not been loaded yet (videoElement.readyState === 0).
- Video file is audio-only.
- The new disablePictureInPicture attribute is present on the video element.
- **The call was not made in a user gesture event handler (e.g. a button click).**

**Comment by std4453** [comment]
好吧……这跟fullscreen API差不多……
不过能否有折衷的解决方案？
比如换p的时候自动取消pip（我看了一下这个不需要用户事件），然后弹个通知/在页面上显示一个快捷的pip按钮之类的……

**Comment by jjj201200** [comment]
@std4453 放完自动取消是可以的。
”弹个通知/在页面上显示一个快捷的pip按钮“这种方式是由于上述的原因而存在的。
我担心更多的操作流程会对大多数不了解的用户产生困扰。
另外暂不清楚窗口内的用户操作和窗口外的用户操作是否拥有同样的作用。
暂且先请手动进行切换的操作。

**Comment by jjj201200** [comment]
b站自己已经实现了无缝切换，应该是相关规范支持了
